version: '3'

services:

  mariadb:
    container_name: mariadb-inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception-backend
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
    restart: unless-stopped

  nginx:
    container_name: nginx-inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception-frontend
    ports:
      - 443:443
    volumes:
      - wp_volume:/var/www
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    container_name: wordpress-inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception-frontend
      - inception-backend
    ports:
      - 9000:9000
    volumes:
      - wp_volume:/var/www
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: ${INCEPTION_DATA_DIR?:err}/wp
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: ${INCEPTION_DATA_DIR?:err}/db
      o: bind
      type: none

networks:
  inception-backend:
  inception-frontend:
