version: "3.9"
services:
    # wp:
    #   container_name: inception-wordpress
    #   build:
    #     context: ./requirements/wordpress
    #     dockerfile: Dockerfile
      # network: host
  server:
    container_name: inception-nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
  # db:
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: test_db
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql
